version: '3'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8082:80"
    environment:
      WORDPRESS_DB_HOST: mysql_db
      WORDPRESS_DB_PASSWORD: examplepassword

  service7:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8083:80"
    environment:
      PMA_HOST: mysql_db
      PMA_USER: root
      PMA_PASSWORD: examplepassword
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"

  mysql:
    image: mysql:latest
    container_name: thirudb
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
    ports:
      - "3308:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: examplepassword
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

